kind: Service
apiVersion: v1
metadata:
  name: uikit-service
spec:
  selector:
    jenkins: uikit
    uikit: uikit
  ports:
    - name: uikit
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 35.197.107.213
