kind: Service
apiVersion: v1
metadata:
  name: uikit-service
  namespace: jenkins
spec:
  selector:
    jenkins: uikit
    uikit: uikit
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 35.197.107.213
  loadBalancerSourceRanges:
    - 207.242.51.98/32
    - 192.195.83.11/32
    - 125.19.67.142/32
