apiVersion: v1
kind: Pod
metadata:
  generateName: uikit-
  labels:
    jenkins: uikit
    uikit: uikit
  namespace: jenkins
spec:
  nodeSelector:
    purpose: 'ui-medium'
  containers:
    - name: uikit
      image: node
      resources:
        requests:
          memory: 5Gi
          cpu: 1500m
      volumeMounts:
        - mountPath: /jenkins-storage
          name: volume-0
      command: ['bash']
      args:
        [
          '/jenkins-storage/ui/uikit/v$VERSION/scripts/docs-runner.sh',
          '/jenkins-storage/ui/uikit/v$VERSION',
          '$GITHUB_HARNESS_BOT_TOKEN',
        ]
  volumes:
    - name: volume-0
      persistentVolumeClaim:
        claimName: nfs
  restartPolicy: Never
