name: Cypress

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Start Documentation Site
        run: |
          yarn start &
          npx wait-on http://localhost:3000
        env:
          CI: true
      - uses: kingscooty/actions-yarn-cy@master
        with:
          cmd: run
          args: test:run
        env: 
          CI: true
