name: Cypress

on: [push]

jobs:
  build:
    name: Build and Run Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Github Package Registry scope
        uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com
          scope: '@wings-software'
      - name: Set up Github Package Registry token
        run: |
          echo @wings-software:registry=https://npm.pkg.github.com > ~/.npmrc
          echo ${{ secrets.GITHUB_HARNESS_BOT_TOKEN }} >> ~/.npmrc
          echo always-auth=true >> ~/.npmrc
      - uses: kingscooty/actions-yarn-cy@master
      - name: Start Docs, and Run Tests
        run: |
          yarn dep
          ./node_modules/.bin/tsc --emitDeclarationOnly --declarationDir ./docs/static/
          NODE_ENV=development ./node_modules/.bin/webpack
          cd docs
          ./node_modules/.bin/next &
          npx wait-on http://localhost:3000
          cd ..
          yarn test
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
