name: Lint
on: [push]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up token
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com
          scope: '@wings-software'
      - name: Lint
        run: |
          npm install
          npm run lint
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
