name: Lint
on: [push]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Github Package Registry scope
        uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com
          scope: '@wings-software'
      - name: Set up Github Package Registry token
        run: |
          echo @wings-software:registry=https://npm.pkg.github.com > ~/.npmrc
          echo ${{ secrets.GITHUB_HARNESS_BOT_TOKEN }} >> ~/.npmrc
          echo always-auth=true >> ~/.npmrc
      - name: Lint
        run: |
          yarn install
          yarn lint
