name: Lint
on: [push]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        run: |
          yarn install
          yarn lint
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_HARNESS_BOT_TOKEN}}
