name: Lint
on: [push]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        run: |
          yarn install
          yarn lint
