name: Lint
on: [push]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: 'Setup GPR Token'
        run: |
          echo @wings-software:registry=https://npm.pkg.github.com/wings-software > ~/.npmrc
          echo //npm.pkg.github.com/:_authToken=${{secrets.GITHUB_HARNESS_BOT_TOKEN}} >> ~/.npmrc
          echo always-auth=true >> ~/.npmrc
      - name: Lint
        run: |
          yarn dep
          yarn lint
