name: Lint
on: [push]
jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: 'Setup Node'
        uses: actions/setup-node@v1
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_HARNESS_BOT_TOKEN}}
      - name: Lint
        run: |
          yarn dep
          yarn lint
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_HARNESS_BOT_TOKEN}}
